name: Package Publish - CI/CD

on:
 # schedule:
 #   - cron: "30 8 * * *"
  workflow_dispatch:

jobs:
  get_input:
    runs-on: ubuntu-latest
    outputs:
      repo_stat: ${{ steps.set-repo_stat.outputs.repo_stat }}
      date: ${{ steps.date.outputs.date }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          path: main

      - name: Change script permission
        run: chmod +x main/.github/scripts/repo_commit_message_check.sh

      - name: setup gh
        run: echo ${{secrets.PAT}} | gh auth login --with-token
        
      - name: Repo commit message check
        id: repo-commit-message-check
        run: | 
         bash main/.github/scripts/repo_commit_message_check.sh ${{ github.event.repository.name }}
         ls -al
         echo "repo_list_to_publish=$(tail -n 1 without_bump_version.txt)" >> "$GITHUB_OUTPUT"
         echo "repo_list_dont_publish=$(tail -n 1 with_bump_version.txt)" >> "$GITHUB_OUTPUT"

      - name: Generate output json
        id: generate
        run: |
          if [ "${{ github.event.inputs.repo_names }}" -eq "" ]; then
           input_repos=$(echo "core, native-web, native-mobile, styles" | sed 's/[^, ]\+/\\\"&\\\"/g')
           echo "input_repos=$input_repos" >> "$GITHUB_ENV"
          else 
           input_repos=$(echo "${{steps.repo-commit-message-check.outputs.repo_list_to_publish}}" | sed 's/[^, ]\+/\\\"&\\\"/g')
           echo "input_repos=$input_repos" >> "$GITHUB_ENV"
          fi

      - name: Set repo names output
        id: set-matrix
        run: |
          #echo "::set-output name=matrix::{\"repo_names\":[\"core\",\"styles\"]}"
          echo "::set-output name=matrix::{\"repo_names\":[${{env.input_repos}}]}"
      - name: Echo repos_names
        run: echo ${{ steps.set-matrix.outputs.matrix}}

      # - name: Echo only repo names array
      #   run: ${{ toJSON(fromJSON(steps.set-matrix.outputs.matrix).repo_names) }}

      - name: Set repo_stat
        id: set-repo_stat
        run: |
         if [ "$(expr length "${{ toJSON(fromJSON(steps.set-matrix.outputs.matrix).repo_names) }}")" -eq "$(expr length "${{ toJSON(fromJSON('[]')) }}")" ]; then
            echo "::set-output name=repo_stat::failed"
          else
            echo "::set-output name=repo_stat::success"
          fi

      - name: Echo repo stat
        run: echo ${{ steps.set-repo_stat.outputs.repo_stat }}

      - name: Get current IST date
        id: date
        run: echo "::set-output name=date::$(TZ='Asia/Kolkata' date +'%d %B %y %T')"
        
      - name: Read with_bump_version file content
        id: read-with-bump-version-file
        run: echo "::set-output name=file_content::$(cat with_bump_version.txt)"

      - name: Send mail
        if: ${{ steps.read-with-bump-version-file.outputs.file_content != '' }}
        uses: dawidd6/action-send-mail@v3
        with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{secrets.MAIL_USERNAME}}
            password: ${{secrets.MAIL_PASSWORD}}
            secure: true
            from: Wrappid Care
            to: ${{secrets.IDS}}
            cc: ${{secrets.MAINTAINER_ID}}
            subject: No new commits since the last publish.
            body: |
              Hi Wrappid Managers,

              There were no new commits since the last publish in ${{steps.repo-commit-message-check.outputs.repo_list_dont_publish}} package repositories as of ${{ steps.date.outputs.date }}. Therefore, no release or publish is needed.
              
              Thank you for your attention and cooperation.

              Thanks and Regards,
              wrappidcare

              generated by fast-publish github action workflow
            # html_body: file://packagename_version.txt
            ignore_cert: true
            convert_markdown: true
            # attachments: attachments.zip,git.diff
            priority: normal
  job2:
    name: test-build
    runs-on: ubuntu-latest
    needs: [get_input]
    if: needs.get_input.outputs.repo_stat == 'success'
    permissions: write-all

    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

          
      - name: Setup Node Env
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/wrappid
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ github.event.repository.name }}
          NODE_AUTH_TOKEN: ${{secrets.WRAPPID_REGISTRY_TOKEN}}

      - name: List Directories
        id: lsdir
        run: |
          ls -l

      - run: |
         rm -rf .husky
         npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.WRAPPID_REGISTRY_TOKEN}}

      - name: Testing build ${{ github.event.repository.name }}
        run: npm run build

  job3:
    name: checkout-build-publish
    runs-on: ubuntu-latest
    needs: [job2,get_input]
    if: always() && needs.job2.result == 'success'
    permissions: write-all
    strategy:
      matrix: ${{fromJson(needs.get_input.outputs.matrix)}}
#     outputs:
#       ${{matrix.repo_names}}_result: ${{steps.lsdir.outputs.test}}
    # env:
    #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    
    
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3
      
      - name: Delete scripts from ${{ matrix.repo_names }}
        run: |
          pwd
          cd .github
          pwd
          ls -al scripts
          rm -rf scripts
          ls -al
          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

          
      - name: Setup Node Env
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/wrappid
          token: ${{secrets.PUBLISH_TOKEN}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ matrix.repo_names }}
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_TOKEN}}

      - name: List Directories
        id: lsdir
        run: |
          ls -l

      - name: Extract version
        id: extract_version
        run: |
          echo "version=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print version
        run: echo ${{ steps.extract_version.outputs.version }}
      
      # - name: Create Release
      #   id: create_release
      #   run: bash .github/scripts/create_release.sh ${{secrets.GITHUB_TOKEN}} ${{ matrix.repo_names }} ${{ steps.extract_version.outputs.version }}

      - name: setup gh
        run: echo ${{secrets.PAT}} | gh auth login --with-token

      - name: Get tags
        run: git fetch --tags origin

      - name: Create tag
        run: git tag v${{ steps.extract_version.outputs.version }} && git push origin v${{ steps.extract_version.outputs.version }}
        
      - name: Generate Release notes
        run: bash .github/scripts/release_notes.sh ${{ matrix.repo_names }}


# Release not releasing with proper name
      - name: Create Release
        id: create_release
        run: |
          gh config set prompt disabled
          gh release create v${{ steps.extract_version.outputs.version }} -R wrappid/${{ matrix.repo_names }} --notes-file RELEASE_NOTES.md --title "v${{ steps.extract_version.outputs.version }}"

        # uses: softprops/action-gh-release@v1
        # with:
        #   tag_name: v${{ steps.extract_version.outputs.version }}
        #   token: ${{ secrets.PAT }}
        # env:
        #   GITHUB_REPOSITORY: wrappid/${{ matrix.repo_names }}

        
      - name: Install node modules
        run: |
         rm -rf .husky
         npm ci


      - name: Generate ATTRIBUTIONS.md
        run: |
         npm run attributions:gen
         bash ./.github/scripts/attribution_header_adder.sh ${{ github.event.repository.name }}

      - name: Check Build
        run: npm run build

        ##publish
      - name: Publish
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_TOKEN}}

      - name: Bump Version
        id: bump-version
        run: echo "commit_message=$(bash .github/scripts/version_bump.sh)" >> "$GITHUB_OUTPUT"
        # env:
        #   NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: setup git config
        run: |
          # setup the username and email.
          git config user.name "WRAPPID"
          git config user.email "wrappid.framework@gmail.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: commit attribuitions
        run: |
          git pull
          git add ATTRIBUTIONS.md
          git commit -m "${{ env.ATTRIBUTIONS_COMMIT_MESSAGE }}"
            
      - name: commit
        run: |
          # Pull, stage the file, commit and push
          git pull
          git add package.json package/package.json
          git commit -m "${{steps.bump-version.outputs.commit_message}}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{secrets.MAIL_USERNAME}}
            password: ${{secrets.MAIL_PASSWORD}}
            secure: true
            from: Wrappid Care
            to: ${{secrets.IDS}}
            cc: ${{secrets.MAINTAINER_ID}}
            subject: Published - ${{ matrix.repo_names }} - ${{ steps.extract_version.outputs.version }} Package. 🚀

            html_body: |
              <html lang="en">

              <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Exciting News from Wrappiders</title>
              </head>

              <body>
                <p>Hi Wrappiders,</p>

                <p>We have some exciting news to share with you! 🎉<br>
                  We have published a new version of our ${{ matrix.repo_names }}, ${{ steps.extract_version.outputs.version }}. 🚀<br>
                  This version comes with some amazing new features and improvements that will make your experience with our package even better.
                  You can check out the details on our <a href="https://github.com/wrappid/${{ matrix.repo_names }}/releases/latest">${{ matrix.repo_names }} page</a>.
                </p>

                <p>We hope you enjoy using our framework, and we would love to hear your feedback.
                  Please feel free to <a href="mailto:wrappid.framework@gmail.com">contact us</a> if you have any questions or suggestions.
                </p>

                <p>Thank you for your continued support and trust in us. 😊</p>

                <p>Thanks and Regards,<br>
                  ${{github.actor}}<br>
                  (Generated by the fast-publish GitHub Action workflow)</p>
              </body>

              </html>
            ignore_cert: true
            convert_markdown: true
            # attachments: attachments.zip,git.diff
            priority: normal
