name: Publish Package

on:
  workflow_dispatch:
    branches:
      - development
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed
  repository_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    # Runs this job if workflow_dispatch event occurs or if workflow run event is success
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    name: Deploy

    steps:
      - name: Checkout...
        uses: actions/checkout@v3
      
      - name: get release
        run: |
          gh release download --pattern '*.tgz'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/wrappid
          token: ${{secrets.PUBLISH_TOKEN}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path:  ${{ github.event.repository.name }}
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_TOKEN}}
    
      - name: Publish Release
        run: npm run publish
