name: Run Node Script
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Show working directory and list files
        run: echo $PWD && ls -al
        
      - name: Run Node script
        run: node .github/scripts/nodescripts/helloworld.js
